---
version: "3.9"

x-build:
  &default-build
  context: .
  dockerfile: Dockerfile

x-app-vars:
  &default-app-vars
  DAGSTER_POSTGRES_HOSTNAME: "postgresql"
  DAGSTER_POSTGRES_DB: "postgres_db"
  DAGSTER_POSTGRES_USER: "postgres_user"
  DAGSTER_POSTGRES_PASSWORD: "postgres_password"

x-ucr-service:
  &default-ucr-service
  restart: always
  environment:
    << : *default-app-vars
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
  depends_on:
    - localstack
  profiles:
    - dagster
  volumes:
    - ./pipeline/workspaces:/opt/dagster/dagster_home/workspaces
    - ./dbt_test_project:/opt/dagster/dagster_home/dbt_test_project
  networks:
    - dagster_network

services:
  dev:
    build:
      <<: *default-build
      target: dev
    container_name: dev
    # restart: on-failure
    environment:
      <<: *default-app-vars
    ports:
      - "8787:8787"
    depends_on:
      - postgresql
    profiles:
      - dagster
    volumes:
      - ./:/project
      - ./pipeline/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./pipeline/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network

  # ----------------------------------------- #
  #                  Dagster
  # ----------------------------------------- #
  dagit:
    build:
      << : *default-build
      target: dagit
    container_name: dagit
    restart: on-failure
    environment:
      << : *default-app-vars
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    profiles:
      - dagster
    volumes:
      - ./pipeline/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./pipeline/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network

  dagster-daemon:
    build:
      << : *default-build
      target: daemon
    container_name: dagster-daemon
    restart: on-failure
    environment:
      << : *default-app-vars
    depends_on:
      - postgresql
    profiles:
      - dagster
    volumes:
      - ./pipeline/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./pipeline/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network

  # ----------------------------------------- #
  #                 Storage
  # ----------------------------------------- #
  postgresql:
    image: postgres:11
    container_name: postgresql
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
    profiles:
      - dagster
    volumes:
      - ./pipeline/postgres-dagster:/var/lib/postgresql/data
    networks:
      - dagster_network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    profiles:
      - dagster
    networks:
      - dagster_network

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      HOSTNAME: localhost
      SERVICES: s3
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DEFAULT_REGION: us-east-1
    volumes:
      - ./pipeline/data://opt/code/localstack/data
      - ./pipeline/local_stack.sh:/docker-entrypoint-initaws.d/create_localstack_infra.sh
    networks:
      - dagster_network

  # ----------------------------------------- #
  #                   UCR
  # ----------------------------------------- #
  gems:
    << : *default-ucr-service
    build:
      << : *default-build
      target: gems
      # args:
      #   COURSE_WEEK: pipeline
    container_name: gems

  gdw:
    << : *default-ucr-service
    build:
      << : *default-build
      target: gdw
      # args:
      #   COURSE_WEEK: pipeline
    container_name: gdw

  # challenge:
  #   << : *default-ucr-service
  #   build:
  #     << : *default-build
  #     target: challenge
  #     args:
  #       COURSE_WEEK: pipeline
  #   container_name: challenge

networks:
  dagster_network:
    driver: bridge
    name: dagster_network

volumes:
  postgresql:
